---
# This playbook deploys the whole application stack in this site.

- name: configure fc_hosts
  any_errors_fatal: true
  hosts: fc_hosts
  remote_user: root
  roles:
    - fc_hosts

- name: configure eseries for splunk
  any_errors_fatal: true
  hosts: splunk_eseries
  connection: local
  remote_user: root
  roles:
    - splunk_eseries

