---
# Do some stuff on eseries array


- name: Disk_Pool_SSD
  netapp_e_storagepool:
    ssid: "{{ ssid }}"
    api_url: "{{ api_url }}"
    api_username: "{{ api_username }}"
    api_password: "{{ api_password }}"
    criteria_drive_count: 24
    criteria_drive_type: ssd
    name: Disk_Pool_SSD1
    raid_level: raidDiskPool
    state: present
    validate_certs: "{{ validate_certs }}"

- name: Volume Creation
  netapp_e_volume:
    ssid: "{{ ssid }}"
    api_url: "{{ api_url }}"
    api_username: "{{ api_username }}"
    api_password: "{{ api_password }}"
    validate_certs: "{{ validate_certs }}"
    name: "{{ item }}"
    state: present
    storage_pool_name: Disk_Pool_SSD1
    # TODO(lorenp): Dynamically figure out based on sizing
    size: 25
    size_unit: pct
  with_sequence: start=0 end=3 format=Volume%02x

- name: Host Ports
  netapp_e_host:
    ssid: "{{ ssid }}"
    api_url: "{{ api_url }}"
    api_username: "{{ api_username }}"
    api_password: "{{ api_password }}"
    validate_certs: "{{ validate_certs }}"
    host_type_index: 28
    name: "{{ item}}"
    state: present
    ports: 
      "{{ hostvars[item]['fc_ports'] }}"
  with_inventory_hostnames:
    - fc_hosts


#- name: Map Volumes
#  netapp_e_lun_mapping:
#    ssid: "{{ ssid }}"
#    api_url: "{{ api_url }}"
#    api_username: "{{ api_username }}"
#    api_password: "{{ api_password }}"
#    validate_certs: "{{ validate_certs }}"
#    state: present
#    target: host1
#    target_type: host
#    volume_name: Volume1

