---

- name: Verify DMMP
  service: name=multipathd state=started
#  register: dmmp_status

#- debug: var=dmmp_status.status.SubState

#- assert: { that: dmmp_status.status.SubState == "running"}


- name: WWN
  shell: cat /sys/class/fc_host/host*/port_name | cut -c 3-
  register: wwn
  tags: wwn

- name: Gather FC ports
  set_fact:
    fc_ports: "{{ fc_ports| default([])  + [ {'type': 'fc' , 'label':item , 'port':item } ]}}"
  with_items:
    - "{{ wwn.stdout_lines }}"
  when: wwn.stdout_lines is defined

