---

- name: WWN
  shell: cat /sys/class/fc_host/host*/port_name | cut -c 3-
  register: wwn
  tags: wwn

#- name: set WWN fact
#  set_fact: 
#    wwn_fact: wwn.stdout_lines
#    tags: fact



- name: Try somethign else
  set_fact:
    fc_ports: "{{ fc_ports| default([])  + [ {'type': 'fc' , 'label':item , 'port':item } ]}}"
  with_items:
    - "{{ wwn.stdout_lines }}"


- debug: var=fc_ports
